language: python
dist: xenial
sudo: true

python:
  - '3.7'

service:
  - docker

install:
  - sudo apt-get install jq

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - publish.sh